# pylint: disable=no-member
import pygame
pygame.init()
from Classes.character import Character
from Classes.area import Area
screen_width = pygame.image.load("src/Sprites/background_full.png").get_width()
screen_height = pygame.image.load("src/Sprites/background_full.png").get_height()
wall = pygame.image.load("src/Sprites/wall_length.png").get_height()

def generate_map(pick):
    """Generates the chosen map by creating and linking all the areas in it. Returns the starting room and the boss in a list."""
    if pick == 1:
        boss = Character("Necromancer",pygame.image.load("src/Sprites/necromancer2.png"),pygame.image.load("src/Sprites/necromancer1.png"))
        boss.boss = True
        boss.monster = True
        boss.x = screen_width / 2 - boss.over_sprite.get_width() / 2
        boss.y = screen_height - wall - boss.over_sprite.get_height()
        start = Area(pygame.image.load("src/Sprites/background_top.png"))
        area1 = Area(pygame.image.load("src/Sprites/background_left_right_bottom.png"))
        area2 = Area(pygame.image.load("src/Sprites/background_right_top.png"))
        area3 = Area(pygame.image.load("src/Sprites/background_left_right.png"))
        area4 = Area(pygame.image.load("src/Sprites/background_top_bottom.png"))
        area5 = Area(pygame.image.load("src/Sprites/background_left_top.png"))
        area6 = Area(pygame.image.load("src/Sprites/background_full.png"))
        area7 = Area(pygame.image.load("src/Sprites/background_right_top_bottom.png"))
        area8 = Area(pygame.image.load("src/Sprites/background_top_bottom.png"))
        area9 = Area(pygame.image.load("src/Sprites/background_top_bottom.png"))
        area10 = Area(pygame.image.load("src/Sprites/background_left.png"))
        area11 = Area(pygame.image.load("src/Sprites/background_right_bottom.png"))
        area12 = Area(pygame.image.load("src/Sprites/background_top_bottom.png"))
        area13 = Area(pygame.image.load("src/Sprites/background_left_right.png"))
        area14 = Area(pygame.image.load("src/Sprites/background_left_bottom.png"))
        area15 = Area(pygame.image.load("src/Sprites/background_left_bottom.png"))
        area16 = Area(pygame.image.load("src/Sprites/background_left_right.png"))
        area17 = Area(pygame.image.load("src/Sprites/background_top_bottom.png"))
        area18 = Area(pygame.image.load("src/Sprites/background_right_bottom.png"))
        area19 = Area(pygame.image.load("src/Sprites/background_left_top.png"))
        area20 = Area(pygame.image.load("src/Sprites/background_top_bottom.png"))
        area21 = Area(pygame.image.load("src/Sprites/background_left_top_bottom.png"))
        area22 = Area(pygame.image.load("src/Sprites/background_right_top_bottom.png"))
        area23 = Area(pygame.image.load("src/Sprites/background_left_right.png"))
        area24 = Area(pygame.image.load("src/Sprites/background_left_top.png"))
        area25 = Area(pygame.image.load("src/Sprites/background_left_right.png"))
        area26 = Area(pygame.image.load("src/Sprites/background_left_right_bottom.png"))
        area27 = Area(pygame.image.load("src/Sprites/background_right_bottom.png"))
        area28 = Area(pygame.image.load("src/Sprites/background_right_top.png"))
        area29 = Area(pygame.image.load("src/Sprites/background_top_bottom.png"))
        area30 = Area(pygame.image.load("src/Sprites/background_top_bottom.png"))
        area31 = Area(pygame.image.load("src/Sprites/background_left_right.png"))
        boss_room = Area(pygame.image.load("src/Sprites/background_top.png"))

        start.set_neighbours(None,None,area1,None)
        area1.set_neighbours(area2,area3,None,start)
        area2.set_neighbours(None,area1,area4,None)
        area3.set_neighbours(area1,area5,None,None)
        area4.set_neighbours(None,None,area6,area2)
        area5.set_neighbours(area3,None,area7,None)
        area6.set_neighbours(area23,area10,area8,area4)
        area7.set_neighbours(None,area31,area9,area5)
        area8.set_neighbours(None,None,area12,area6)
        area9.set_neighbours(None,None,area11,area7)
        area10.set_neighbours(area6,None,None,None)
        area11.set_neighbours(None,area13,None,area9)
        area12.set_neighbours(None,None,area14,area8)
        area13.set_neighbours(area11,area15,None,None)
        area14.set_neighbours(area16,None,None,area12)
        area15.set_neighbours(area13,None,None,area17)
        area16.set_neighbours(area18,area14,None,None)
        area17.set_neighbours(None,None,area15,area19)
        area18.set_neighbours(None,area16,None,area20)
        area19.set_neighbours(area31,None,area17,None)
        area20.set_neighbours(None,None,area18,area21)
        area21.set_neighbours(area25,None,area20,area22)
        area22.set_neighbours(None,area23,area21,area24)
        area23.set_neighbours(area22,area6,None,None)
        area24.set_neighbours(area26,None,area22,None)
        area25.set_neighbours(area27,area21,None,None)
        area26.set_neighbours(area28,area24,None,area30)
        area27.set_neighbours(None,area25,None,area29)
        area28.set_neighbours(None,area26,area29,None)
        area29.set_neighbours(None,None,area27,area28)
        area30.set_neighbours(None,None,area26,boss_room)
        area31.set_neighbours(area7,area19,None,None)
        boss_room.set_neighbours(None,None,area30,None)

        start.set_start_location()
        boss_room.set_boss_room()
        return (start,boss)
